### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by JaxkDev** [alfieH0/Assignment-1#2]
Just starting with some small errors that I have found,

Without checking the function input against the size of the remaining pack this can lead to index out of range.
https://github.com/alfieH0/Assignment-1/blob/8463d903533ffef3e70fddc7441052c692547b97/CMP1903M%20A01%202223/Pack.cs#LL70

While there is enums for Suit which I quite like, have you considered some error (set validation) handling for `Value`?
https://github.com/alfieH0/Assignment-1/blob/8463d903533ffef3e70fddc7441052c692547b97/CMP1903M%20A01%202223/Card.cs#L23

Is there a special thing for 7 riffle shuffles specifically here? A comment there could be sufficient.
https://github.com/alfieH0/Assignment-1/blob/8463d903533ffef3e70fddc7441052c692547b97/CMP1903M%20A01%202223/Pack.cs#L42

The code could be improved slightly here by having it fill the pack outside the switch since it happens on every case.
https://github.com/alfieH0/Assignment-1/blob/8463d903533ffef3e70fddc7441052c692547b97/CMP1903M%20A01%202223/Pack.cs#L34

Error handling could be improved as mentioned at the start but otherwise there is evidence of some error handling!
https://github.com/alfieH0/Assignment-1/blob/8463d903533ffef3e70fddc7441052c692547b97/CMP1903M%20A01%202223/Pack.cs#L31
https://github.com/alfieH0/Assignment-1/blob/8463d903533ffef3e70fddc7441052c692547b97/CMP1903M%20A01%202223/Pack.cs#L53

Overall a very solid piece of work, just some touchups here and there.
And at those points that didn't seem clear a simple bit of documentation will suffice :)
 
Jack Honour 27203747

**Comment by alfieH0** [comment]
thanks for the very clear and thorough feedback as per your feedback I have done error handling throughout the whole program now so that it will no longer cause any errors when being messed with 

I also decided to remove the 7 riffle shuffles as I no longer see them as necessary and it will now just do one perfect riffle shuffle

as per your suggestion I also did `call.FillDeck();` outside of the switch case to further neaten up my code ever so slightly
